title: Cognitive offloading
description: Emptying the mind, one article at a time
author: J. Lemaire
email: jeremy.lemaire (@) gmail.com
url: "https://jeremylem.github.io"
og_image: /assets/xray-brain3.png

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-feed

# Site Author
author:
  name: "J. Lemaire"
  bio: "Emptying the mind, one article at a time"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jeremylem"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jeremylem"


# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      toc: true
      toc_sticky: true
      author_profile: true
      header:
        overlay_image: /assets/xray-brain3.png
        overlay_filter: 0.5

markdown: kramdown
kramdown:
  input: GFM
