title: Cognitive offloading
description: Emptying the mind, one article at a time
author: Jeremy Lemaire
email: jeremy.lemaire (@) gmail.com
theme: "overkyll-jekyll-theme"
markdown: kramdown
kramdown:
  input: GFM
